version: '3.8'
services:

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: ililBooks
#    ports:
#      - "8081:8081"
#    depends_on:
##      - db
##      - elasticsearch
##      - redis
#      elasticsearch:
#        condition: service_healthy
#      db:
#        condition: service_healthy
#      redis:
#        condition: service_started
#    environment:
#      - SPRING_DATASOURCE_URL=${DB_URL_DOCKER}
#      - SPRING_DATASOURCE_USERNAME=${DB_USER}
#      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
#      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
#      - BOOK_API_KEY=${BOOK_API_KEY}
#      - SPRING_PROFILES_ACTIVE=docker
#      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}      # 추가
#      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} # 추가
#      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}       # 추가
#      - AWS_REGION=${AWS_REGION}
#    networks:
#      - esnet
#
#    env_file:
#      - .env  # .env 파일 로드


  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_DATABASE=ililBooks
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - esnet
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-prhm1031hr!' ]
      timeout: 20s
      retries: 10

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - esnet
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.5
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false   # 보안 비활성화
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

    command: >
      bash -c "
      bin/elasticsearch-plugin install analysis-nori &&
      /usr/local/bin/docker-entrypoint.sh elasticsearch"
    ports:
      - "9200:9200"
    networks:
      - esnet
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsSL http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 30s
      retries: 10

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.5
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - esnet

volumes:
  mysql-data:
  esdata:

networks:
  esnet:
    driver: bridge
