server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 1800

spring:
  config:
    import: optional:file:.env[.properties]
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: ilil-books

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

book:
  api:
    key: ${BOOK_API_KEY}

cloud:
  aws:
    region: ${AWS_REGION}
    credentials:
      secret-key: ${AWS_SECRET_ACCESS_KEY}
      access-key: ${AWS_ACCESS_KEY_ID}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}

client:
   naver:
      client-id: ${NAVER_CLIENT_ID}
      client-secret: ${NAVER_CLIENT_SECRET}
      redirect-uri: ${NAVER_REDIRECT_URI}
   google:
      client_id: ${GOOGLE_CLIENT_ID}
      client_secret: ${GOOGLE_CLIENT_SECRET}
      redirect_uri: ${GOOGLE_REDIRECT_URI}