server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 1800

spring:
  config:
    import: optional:file:.env[.properties]
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: ilil-books

  datasource:
    url: ${DOCKER_DB_URL}
    username: ${DOCKER_MYSQL_USER}
    password: ${DOCKER_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    template:
      default-receive-queue: order-mail-queue # queue 이름
      exchange: order.mail.exchange #producer가 데이터를 보낼 교환소
      routing-key: order.mail

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

book:
  api:
    key: ${BOOK_API_KEY}

cloud:
  aws:
    region: ${AWS_REGION}
    credentials:
      secret-key: ${AWS_SECRET_ACCESS_KEY}
      access-key: ${AWS_ACCESS_KEY_ID}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}