name: build and test

on:
  push:
    branches:
      - dev
#      - feat/ci_cd # 테스트용

  pull_request:
    branches:
      - dev
    types:
      - closed

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Give permission to gradlew
        run: chmod +x ./gradlew

      - name: Run tests with coverage verification
        run: ./gradlew clean testCoverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  notify:
    name: Send Notification
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Notify via Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "build and run test 완료하였습니다"
        if: always()
